<?php

defined( 'ABSPATH' ) || exit;

final class AssessCraft_Mail_Diagnostics {
	private const OPTION = 'assesscraft_mail_diagnostics';

	private static ?WP_Error $captured_error = null;

	public static function register(): void {
		add_action( 'admin_post_assesscraft_send_test_email', array( self::class, 'handle_test_email' ) );
	}

	public static function send( string $recipient, string $subject, string $body, array $headers = array(), array $context = array() ): bool {
		$recipient = sanitize_email( $recipient );
		$subject   = sanitize_text_field( $subject );
		$context   = self::sanitize_context( $context );

		if ( ! $recipient || ! is_email( $recipient ) ) {
			self::record( 'failed', $recipient, $subject, __( 'The configured recipient email address is invalid.', 'assesscraft' ), $context );
			return false;
		}

		self::$captured_error = null;
		add_action( 'wp_mail_failed', array( self::class, 'capture_failure' ) );
		$accepted = wp_mail( $recipient, $subject, $body, $headers );
		remove_action( 'wp_mail_failed', array( self::class, 'capture_failure' ) );

		$error_message = '';
		if ( self::$captured_error instanceof WP_Error ) {
			$error_message = self::$captured_error->get_error_message();
		}
		if ( ! $accepted && ! $error_message ) {
			$error_message = __( 'WordPress mail returned false without an additional transport error.', 'assesscraft' );
		}

		self::record( $accepted ? 'accepted' : 'failed', $recipient, $subject, $error_message, $context );
		return $accepted;
	}

	public static function capture_failure( WP_Error $error ): void {
		self::$captured_error = $error;
	}

	public static function last_result(): array {
		$result = get_option( self::OPTION, array() );
		return is_array( $result ) ? $result : array();
	}

	public static function handle_test_email(): void {
		if ( ! current_user_can( 'manage_options' ) ) {
			wp_die( esc_html__( 'You do not have permission to send a test email.', 'assesscraft' ) );
		}
		check_admin_referer( 'assesscraft_send_test_email' );

		$recipient = isset( $_POST['recipient'] ) ? sanitize_email( wp_unslash( $_POST['recipient'] ) ) : '';
		$subject   = sprintf(
			/* translators: %s: Website name. */
			__( 'AssessCraft test email from %s', 'assesscraft' ),
			wp_specialchars_decode( get_bloginfo( 'name' ), ENT_QUOTES )
		);
		$body = implode(
			"\n",
			array(
				__( 'This is a test email generated by AssessCraft.', 'assesscraft' ),
				'',
				__( 'If this message arrived, WordPress and the configured mail transport accepted and delivered the test.', 'assesscraft' ),
				__( 'If AssessCraft reports that WordPress accepted the message but it does not arrive, review the SMTP provider logs, sender authentication, spam folder, and domain DNS records.', 'assesscraft' ),
			)
		);

		$accepted = self::send(
			$recipient,
			$subject,
			$body,
			array( 'Content-Type: text/plain; charset=UTF-8' ),
			array( 'operation' => 'test_email' )
		);

		$url = add_query_arg(
			'assesscraft_mail_test',
			$accepted ? 'accepted' : 'failed',
			admin_url( 'edit.php?post_type=' . AssessCraft_Post_Type::TYPE . '&page=assesscraft-system-status' )
		);
		wp_safe_redirect( $url );
		exit;
	}

	public static function render_panel(): void {
		if ( ! current_user_can( 'manage_options' ) ) {
			return;
		}

		$result    = self::last_result();
		$status    = sanitize_key( $result['status'] ?? 'not_tested' );
		$recipient = sanitize_email( $result['recipient'] ?? '' );
		$subject   = sanitize_text_field( $result['subject'] ?? '' );
		$error     = sanitize_text_field( $result['error'] ?? '' );
		$time      = sanitize_text_field( $result['occurred_at'] ?? '' );
		$operation = sanitize_key( $result['operation'] ?? '' );
		$test      = sanitize_key( wp_unslash( $_GET['assesscraft_mail_test'] ?? '' ) );
		?>
		<h2><?php esc_html_e( 'Email delivery diagnostics', 'assesscraft' ); ?></h2>
		<?php if ( 'accepted' === $test ) : ?>
			<div class="notice notice-success inline"><p><?php esc_html_e( 'WordPress accepted the AssessCraft test email. Check the recipient inbox and the SMTP provider log.', 'assesscraft' ); ?></p></div>
		<?php elseif ( 'failed' === $test ) : ?>
			<div class="notice notice-error inline"><p><?php esc_html_e( 'WordPress rejected the AssessCraft test email. Review the error below and your SMTP configuration.', 'assesscraft' ); ?></p></div>
		<?php endif; ?>
		<p><?php esc_html_e( 'AssessCraft uses WordPress mail delivery. An “accepted” result means WordPress or the SMTP plugin accepted the message for sending; it does not guarantee inbox placement.', 'assesscraft' ); ?></p>
		<table class="widefat striped"><tbody>
			<tr><th><?php esc_html_e( 'Last result', 'assesscraft' ); ?></th><td><strong><?php echo esc_html( self::status_label( $status ) ); ?></strong></td></tr>
			<tr><th><?php esc_html_e( 'Operation', 'assesscraft' ); ?></th><td><code><?php echo esc_html( $operation ?: '—' ); ?></code></td></tr>
			<tr><th><?php esc_html_e( 'Recipient', 'assesscraft' ); ?></th><td><code><?php echo esc_html( $recipient ?: '—' ); ?></code></td></tr>
			<tr><th><?php esc_html_e( 'Subject', 'assesscraft' ); ?></th><td><?php echo esc_html( $subject ?: '—' ); ?></td></tr>
			<tr><th><?php esc_html_e( 'Time', 'assesscraft' ); ?></th><td><code><?php echo esc_html( $time ?: '—' ); ?></code></td></tr>
			<tr><th><?php esc_html_e( 'Transport error', 'assesscraft' ); ?></th><td><?php echo esc_html( $error ?: '—' ); ?></td></tr>
		</tbody></table>
		<form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>" style="margin-top:16px;max-width:680px;">
			<input type="hidden" name="action" value="assesscraft_send_test_email">
			<?php wp_nonce_field( 'assesscraft_send_test_email' ); ?>
			<label for="assesscraft-test-recipient"><strong><?php esc_html_e( 'Test recipient', 'assesscraft' ); ?></strong></label>
			<div style="display:flex;gap:8px;align-items:center;margin-top:6px;">
				<input id="assesscraft-test-recipient" class="regular-text" type="email" name="recipient" required value="<?php echo esc_attr( get_option( 'admin_email' ) ); ?>">
				<button class="button button-primary" type="submit"><?php esc_html_e( 'Send test email', 'assesscraft' ); ?></button>
			</div>
		</form>
		<?php
	}

	private static function record( string $status, string $recipient, string $subject, string $error, array $context ): void {
		update_option(
			self::OPTION,
			array(
				'status'        => sanitize_key( $status ),
				'recipient'     => sanitize_email( $recipient ),
				'subject'       => sanitize_text_field( $subject ),
				'error'         => sanitize_text_field( $error ),
				'assessment_id' => absint( $context['assessment_id'] ?? 0 ),
				'operation'     => sanitize_key( $context['operation'] ?? 'consultation_notification' ),
				'occurred_at'   => gmdate( 'c' ),
			),
			false
		);
	}

	private static function sanitize_context( array $context ): array {
		return array(
			'assessment_id' => absint( $context['assessment_id'] ?? 0 ),
			'operation'     => sanitize_key( $context['operation'] ?? 'consultation_notification' ),
		);
	}

	private static function status_label( string $status ): string {
		if ( 'accepted' === $status ) {
			return __( 'Accepted by WordPress mailer', 'assesscraft' );
		}
		if ( 'failed' === $status ) {
			return __( 'Rejected or failed', 'assesscraft' );
		}
		return __( 'No email attempt recorded yet', 'assesscraft' );
	}
}
